services:
  python-data-update-service:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - data-volume:/app/data
    depends_on:
      - neo4j

  neo4j:
    build:
      context: .
      dockerfile: neo4j_apoc.Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - data-volume:/app/data
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always

  grafana:
    image: grafana/grafana:9.5.6
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/files:/var/lib/grafana/files
    command:
      - unzip /var/lib/grafana/files/kniepdennis-neo4j-datasource-1.2.0.zip -d /var/lib/grafana/plugins/kniepdennis-neo4j-datasource

volumes:
  data-volume: {}
  grafana-storage: {}

