services:
  python-data-update-service:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - data-volume:/app/data
    depends_on:
      - neo4j

  neo4j:
    build:
      context: .
      dockerfile: neo4j_apoc.Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - data-volume:/app/data
    environment:
      - NEO4J_AUTH=neo4j/password

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=kniepdennis-neo4j-datasource

volumes:
  data-volume: {}
  grafana-storage: {}

