name: Python integration test
# Source: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

on: [ push ]

jobs:
  integration_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/${{ secrets.NEO4J_LOCAL_PASSWORD }}
        ports:
          - 7474:7474
          - 7687:7687
        options: --health-cmd "curl http://localhost:7474" --health-timeout 10s --health-retries 3 --health-interval 5s

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create config json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG_JSON }}

      - name: Run integration tests
        run: pytest integration_test