name: Python integration test
# Source: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - uses: baptouuuu/setup-neo4j@v1.2.0
      - uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:7474/browser/
          max-attempts: 5
          retry-delay: 5s
          retry-all: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create config json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG_JSON }}

      - name: Run integration tests
        run: pytest integration_test